# Generated by Django 3.0.5 on 2020-10-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact', models.BigIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('AOI_1', models.CharField(max_length=100)),
                ('AOI_2', models.CharField(max_length=100)),
                ('percentage_10', models.IntegerField()),
                ('percentage_12', models.IntegerField()),
                ('percentage_undergrad', models.IntegerField()),
                ('backlogs', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Registration')),
            ],
        ),
    ]
