# Generated by Django 3.1.2 on 2020-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_profileevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileevaluation',
            name='CGPA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileevaluation',
            name='GRE_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileevaluation',
            name='LOR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileevaluation',
            name='Research',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileevaluation',
            name='SOP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileevaluation',
            name='TOEFL_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileevaluation',
            name='backlogs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profileevaluation',
            name='percentage_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileevaluation',
            name='percentage_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileevaluation',
            name='percentage_undergrad',
            field=models.IntegerField(default=0),
        ),
    ]
